### ISSUE TITLE
Errors during tox run

### ISSUE THREAD

**Issue by ditansu** [dry-python/editors#21]
I trying begin write a feature. 

**my steps:**
1. fork repo
2. setup virtualenv 
3. `brew install vale`
4. `$ tox --recreate | tee tox.log`  

**actual result:**
and get below summary 
```
ERROR:   precommit: commands failed
  stories-upgrade: commands succeeded
ERROR:   flake8: commands failed
  bandit: commands succeeded
  xenon: commands succeeded
  mypy: commands succeeded
  vale: commands succeeded
  remarklint: commands succeeded
  yamllint: commands succeeded
  jscpd: commands succeeded
ERROR:   commitlint: commands failed
```
see details in [tox.log](https://github.com/dry-python/editors/files/4185499/tox.log)

pre-commit log [pre-commit.log](https://github.com/dry-python/editors/files/4185548/pre-commit.log)

**expected result**:
install all requirements without errors

**Comment by proofit404** [comment]
Should be solved at this point in master.
- sed issue explained in docs
- pre-commit escape fixed
- flake8 ignore directory fixed

Thanks for the report!
